#!/usr/bin/env sh
set -eu

. "$(dirname "$0")/mcp-env.sh"

usage() {
  cat <<EOF
Usage: $(basename "$0") [--run] [--list] [profile]

Generate or apply a managed Codex MCP profile for Codex Workspace.

Profiles:
  - default-full
  - safe-readonly
  - browser-debug
  - research
  - github-full

Default mode: dry run
Default profile: default-full
EOF
}

list_profiles() {
  cat <<EOF
Available MCP profiles:
- default-full
- safe-readonly
- browser-debug
- research
- github-full
EOF
}

run_mode="dry-run"
profile="default-full"

while [ $# -gt 0 ]; do
  case "$1" in
    --run)
      run_mode="run"
      shift
      ;;
    --list)
      list_profiles
      exit 0
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      profile=$1
      shift
      ;;
  esac
done

case "$profile" in
  default-full|safe-readonly|browser-debug|research|github-full)
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac

ensure_mcp_local_dirs
load_mcp_local_env

playwright_wrapper_escaped=$(toml_escape "$mcp_playwright_wrapper")
chrome_wrapper_escaped=$(toml_escape "$mcp_chrome_wrapper")
docs_url="https://developers.openai.com/mcp"
context7_url="https://mcp.context7.com/mcp"
github_url="https://api.githubcopilot.com/mcp/"
docs_url_escaped=$(toml_escape "$docs_url")
context7_url_escaped=$(toml_escape "$context7_url")
github_url_escaped=$(toml_escape "$github_url")

temp_overlay=$(mktemp "$mcp_local_root/mcp-overlay.XXXXXX")
trap 'rm -f "$temp_overlay" "${temp_validate_dir:-}" "${temp_config_file:-}" "${temp_existing_file:-}" 2>/dev/null || true' EXIT

cat >"$temp_overlay" <<EOF
$mcp_start_marker
# Generated by tools/scripts/install-mcp-profile.sh on $(mcp_timestamp)
# Profile: $profile
# Workspace root: $mcp_workspace_root
# This block is managed by Codex Workspace. Re-run the installer to update it.
EOF

add_openai_docs() {
  cat >>"$temp_overlay" <<EOF

[mcp_servers.openaiDeveloperDocs]
url = "$docs_url_escaped"
EOF
}

add_context7() {
  cat >>"$temp_overlay" <<EOF

[mcp_servers.context7]
url = "$context7_url_escaped"
env_http_headers = { CONTEXT7_API_KEY = "CONTEXT7_API_KEY" }
EOF
}

add_playwright() {
  cat >>"$temp_overlay" <<EOF

[mcp_servers.playwright]
command = "$playwright_wrapper_escaped"
args = []
EOF
}

add_chrome_devtools() {
  cat >>"$temp_overlay" <<EOF

[mcp_servers."chrome-devtools"]
command = "$chrome_wrapper_escaped"
args = []
EOF
}

add_github() {
  cat >>"$temp_overlay" <<EOF

[mcp_servers.github]
url = "$github_url_escaped"
bearer_token_env_var = "GITHUB_PAT"
http_headers = { "X-MCP-Toolsets" = "all" }
EOF
}

case "$profile" in
  default-full)
    add_openai_docs
    add_context7
    add_playwright
    add_chrome_devtools
    add_github
    ;;
  safe-readonly)
    add_openai_docs
    add_context7
    ;;
  browser-debug)
    add_playwright
    add_chrome_devtools
    ;;
  research)
    add_openai_docs
    add_context7
    ;;
  github-full)
    add_github
    ;;
esac

cat >>"$temp_overlay" <<EOF
$mcp_end_marker
EOF

temp_validate_dir=$(mktemp -d)
mkdir -p "$temp_validate_dir/.codex"
temp_config_file="$temp_validate_dir/.codex/config.toml"

if [ -f "$mcp_codex_config_file" ]; then
  remove_managed_mcp_block "$mcp_codex_config_file" >"$temp_config_file"
else
  : >"$temp_config_file"
fi

if [ -s "$temp_config_file" ]; then
  printf '\n' >>"$temp_config_file"
fi
cat "$temp_overlay" >>"$temp_config_file"

HOME="$temp_validate_dir" CODEX_HOME="$temp_validate_dir/.codex" codex mcp list --json >/dev/null 2>/dev/null

printf 'Codex Workspace MCP installer\n'
printf 'Workspace: %s\n' "$mcp_workspace_root"
printf 'Profile: %s\n' "$profile"
printf 'Mode: %s\n' "$run_mode"
printf 'Codex config: %s\n' "$mcp_codex_config_file"
printf 'Generated overlay: %s\n' "$mcp_generated_overlay_file"
printf 'Local env file: %s\n\n' "$mcp_local_env_file"

print_mcp_status "[ok]" "validate" "managed MCP block parses in a temp Codex home"

case "$profile" in
  default-full)
    print_mcp_status "[plan]" "servers" "openaiDeveloperDocs, context7, playwright, chrome-devtools, github"
    ;;
  safe-readonly)
    print_mcp_status "[plan]" "servers" "openaiDeveloperDocs, context7"
    ;;
  browser-debug)
    print_mcp_status "[plan]" "servers" "playwright, chrome-devtools"
    ;;
  research)
    print_mcp_status "[plan]" "servers" "openaiDeveloperDocs, context7"
    ;;
  github-full)
    print_mcp_status "[plan]" "servers" "github"
    ;;
esac

if [ "$run_mode" = "dry-run" ]; then
  print_mcp_status "[plan]" "apply" "re-run with --run to write the overlay and update ~/.codex/config.toml"
  print_mcp_status "[plan]" "health" "tools/scripts/check-mcp-health.sh --profile $profile"
  exit 0
fi

ensure_mcp_local_env_file
cp "$temp_overlay" "$mcp_generated_overlay_file"
printf '%s\n' "$profile" >"$mcp_generated_profile_file"

temp_existing_file=$(mktemp "$mcp_local_root/codex-config.XXXXXX")
if [ -f "$mcp_codex_config_file" ]; then
  remove_managed_mcp_block "$mcp_codex_config_file" >"$temp_existing_file"
else
  : >"$temp_existing_file"
fi

if [ -f "$mcp_codex_config_file" ]; then
  backup_file="$mcp_local_root/config.backup.$(date +%Y%m%d%H%M%S).toml"
  cp "$mcp_codex_config_file" "$backup_file"
  print_mcp_status "[ok]" "backup" "$backup_file"
fi

if [ -s "$temp_existing_file" ]; then
  cat "$temp_existing_file" >"$mcp_codex_config_file"
  printf '\n' >>"$mcp_codex_config_file"
else
  : >"$mcp_codex_config_file"
fi
cat "$mcp_generated_overlay_file" >>"$mcp_codex_config_file"

print_mcp_status "[ok]" "overlay" "$mcp_generated_overlay_file"
print_mcp_status "[ok]" "profile" "$profile"
print_mcp_status "[ok]" "config" "$mcp_codex_config_file"
print_mcp_status "[ok]" "next step" "run tools/scripts/check-mcp-health.sh --profile $profile"
